
### Create a new user
POST http://localhost:3000/users/signup
content-type: application/json

{
    "email": "mail2@mail.com",
    "password": "12345678"
}

### Find a user
GET http://localhost:3000/users/1

### Find all users
GET http://localhost:3000/users?email=mail2@mail.com

### Delete a user
DELETE http://localhost:3000/users/233

### Update a user
PATCH http://localhost:3000/users/13
content-type: application/json

{
    "email": "mail22@mail.com",
    "password": "12345678"
}