@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NjQ3NTc0NTQsImV4cCI6MTc2NDc2MTA1NH0.saXs82BXc8tOHyAbcwhiUoL2-wRYchgEeCWlqnvaNSQ
###

## Register User
POST {{baseUrl}}/users/register
Content-Type: application/json

{
    "email": "admin@test.com",
    "name": "admin",
    "password": "password123",
    "role": "admin"
}

###

## Login
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "admin@test.com",
    "password": "password123"
}

###

## Logout (stateless - just a convenience endpoint)
POST {{baseUrl}}/users/logout
Authorization: Bearer {{token}}
Content-Type: application/json

###

## Get Current User (Protected - requires JWT)
GET {{baseUrl}}/users/me
Authorization: Bearer {{token}}
Content-Type: application/json

###

## Get All Users (Protected - requires JWT + ADMIN role)
GET {{baseUrl}}/users
Authorization: Bearer {{token}}
Content-Type: application/json
