### Test products
GET http://localhost:3000/products/test

### Test categorys
GET http://localhost:3000/products/test-categorys

### Search products
GET http://localhost:3000/products/search-products?search=hoodie

### Get products by category
GET http://localhost:3000/products/get-products-by-category?level=1&categoryId=2FE8A083-5E7B-4179-896D-561EA116F730

### Get warehouse list
GET http://localhost:3000/products/get-warehouse-list

### Get product details
GET http://localhost:3000/products/get-product-details?vsku=CJLT1772562-Black-S